---
title: "TPM table for spike-in normalised RNA-seq of G1 arrested cells-elutration - MS64/MS67"
author: "MS"
date: "240114"
output: html_document
file  names should be formatted: 
---
```{r setup}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
rm(list=ls())
library(MASS)
library(plotly)
library(broom)
library(corrr)
library(nls.multstart)
library(viridis)
library(tidyverse)
load('../../r_functions/functions.rda')
```

load tables, visualize sample info
```{r}
# Create output plots directories
if (!dir.exists("../figures/")) {
  dir.create("../figures/", recursive = TRUE)
}

#load data and annotation tables
df1 <- read_tsv("../input_tables/express-1.5.1.Candida+cerevisiae.2x50mers.TPM_with_both_names.table.txt", show_col_types=FALSE) %>% rename("species"=1, "gene_name"=2, "gene_id"=3)
verified_ORF <- read_tsv("../input_tables/230128_verified_ORF.txt", show_col_types=FALSE) %>% dplyr::select(-"species")
sample_info <- read_tsv("../input_tables/sample_info.txt", show_col_types=FALSE)

#histogram of mean cell size for each strain
mean_cell_size <- sample_info %>% group_by(strain_id, time_point) %>% summarize(mean_size = mean(mean_cell_size), .groups = 'drop')
strain_size <- ggplot(mean_cell_size, aes(x = time_point, y = mean_size)) +
  geom_bar(stat = "identity", fill = "steelblue", alpha=0.8) +
  geom_text(aes(label = round(mean_size, 2)), vjust = -0.5, color = "black", alpha=0.6) +
  labs(x = "Elutriation Arrest Time Points", y = "Mean Cell Size (fL)") +
  facet_wrap(~ strain_id, labeller = as_labeller(c("MS64" = "MS64-haploid", "MS67" = "MS67-diploid"))) +
  theme_classic()
strain_size
strain_size %>% ggsave(filename = "../figures/sample_elutriation-arrest_RNA.svg", dpi = 300, width = 7.5, height = 5)
```

merge TPM datawith annotation data, calculate global ratios, recalculate TPMs for one species and normalize
```{r}
#join dataset to annotation file, filter for genes with TPM > 0 in all samples and pivot TPM longer
df2 <- left_join(df1, verified_ORF, by="gene_id") %>% filter_at(vars(contains("exp")), all_vars(.>0)) %>% pivot_longer(cols=colnames(dplyr::select(., contains("exp"))), names_to="sample", values_to="TPM")

#get TPM sum for each species, combine with sample info and calculate spike-in ratio, RNA per genome and  RNA per cell
norm_table1 <- df2 %>% filter(verified_ORF==TRUE) %>% group_by(species, sample) %>% summarise(TPMsum=sum(TPM)) %>% pivot_wider(names_from=species, names_glue="{species}_{.value}", values_from="TPMsum") %>% mutate(spikein_ratio=S_cerevisiae_TPMsum/Candida_TPMsum) %>% left_join(., sample_info, by="sample") %>% mutate(RNA_per_genome=spikein_ratio/DNA_ratio)%>% mutate(RNA_per_cell=RNA_per_genome*DNA_per_cell)

#average replicates, combine with unaveraged values and normalise to minimum value
norm_table_2 <- norm_table1 %>% group_by(strain_id, time_point) %>% summarise(av_RNA_per_cell = mean(RNA_per_cell)) %>% left_join(norm_table1, ., by=c("strain_id", "time_point")) %>% mutate(RNA_per_cell_norm=RNA_per_cell/min(av_RNA_per_cell))

#average the mean cell size within experiments, MCSe = mean cell size per experiment, MCS = Mean Cell Size
norm_table <- norm_table_2 %>% group_by(experiment) %>% summarise(exp_av_cell_size = mean(mean_cell_size)) %>% left_join(norm_table_2, ., by=c('experiment'))

#filter for budding yeast (sc) reads calculate TPM with and without normalisation
df_sc_1 <- left_join(df2, norm_table, by="sample") %>% filter(., verified_ORF==TRUE, species == "S_cerevisiae") %>% mutate(TPMsc=((TPM/S_cerevisiae_TPMsum)*10^6)) %>% dplyr::select(-species, -verified_ORF)

#normalise all values to the mean and log
df_sc_sum <- df_sc_1 %>% summarise(.by=c(gene_id, gene_name, strain_id), TPMmean=mean(TPMsc), TPMmin=min(TPMsc)) %>% left_join(., summarise(filter(df_sc_1, time_point=="T3"), .by=c(gene_id, strain_id), TPMrefm=mean(TPMsc))) %>% left_join(., summarise(filter(df_sc_1, time_point=="T1"), .by=c(gene_id, strain_id), TPMrefs=mean(TPMsc)))

df_sc <- left_join(df_sc_1, df_sc_sum, by=c('gene_id', 'gene_name', 'strain_id')) %>% mutate(TPMnorm=TPMsc/TPMmean) %>% mutate(log2TPMnorm = log2(TPMsc/TPMmean)) %>% mutate(log2_norm_cell_size = log2(mean_cell_size/exp_av_cell_size))
```

PCA
```{r}
#principle component analysis on all genes with minimum TPM > 5
df_pca <- df_sc %>% dplyr::select(gene_id, sample, log2TPMnorm) %>% pivot_wider(id_cols=c("gene_id"), names_from="sample", values_from=c("log2TPMnorm")) %>% left_join(.,  filter(df_sc_sum, strain_id=="MS64") %>% select(gene_id, TPMmin), by=("gene_id")) %>% filter(TPMmin > 2) %>% select(-TPMmin)
pca <- df_pca %>% dplyr::select(., where(is.numeric)) %>% prcomp(scale.=FALSE, center=FALSE)

pca_results_variance <- summary(pca)$importance[2,] %>% as.data.frame()
pca_results_samples <- as.data.frame(pca$rotation) %>% rownames_to_column(var="sample") %>% left_join(., sample_info)
pca_results_genes <- bind_cols(dplyr::select(df_pca, gene_id), as.data.frame(pca$x))

label<-labs(y="PC1", x="Mean Cell Size (fL)", color="Experiment", title="Elutriation-arrest RNA") 

plot_pca <- pca_results_samples %>% ggplot(aes(x=mean_cell_size, y=PC1, color=experiment, text=paste("", sample_short))) + geom_point(size=3, alpha=0.85) +  viridis::scale_color_viridis(discrete=TRUE) + coord_fixed(ratio = 225) + label
plot_pca
plot_pca %>% ggsave(filename = "../figures/PC1-v-size_elutriation-arrest_RNA.svg", dpi = 300, width = 4, height = 3)
```

CORRELATION ANALYASIS
```{r}
#calcualte correlations between selected TPM values, convert to tidy format and plot
df_corr <- df_sc %>% filter(TPMmin>2) %>% select(gene_id, sample_short, var=log2TPMnorm) %>% pivot_wider(id_cols=c("gene_id") , names_from="sample_short", values_from=c("var"))

plot_cor <- plot_corr(df_corr, title="Elutriation arrest RNA", angle=75, show_corr=F)
plot_cor
plot_cor %>% ggsave(filename = "../figures/pearson-heatmap_elutriation-arrest_RNA.svg", dpi = 300, width = 6, height = 4.5)
```

Linear regression
```{r}
# Construct linear models for average of replicates, save the slope and SE 
df_fit_pooled <- df_sc  %>% nest(data = c(-gene_id, -strain_id)) %>% slope_fit(a="log2TPMnorm", b="log2_norm_cell_size") %>% mutate(replicate="pooled")

# Construct linear models for each replicate separately
df_fit_exp <- df_sc %>% nest(data = c(-gene_id, -replicate, -strain_id)) %>% slope_fit(a="log2TPMnorm", b="log2_norm_cell_size")

df_slopes <- bind_rows(df_fit_exp, df_fit_pooled) %>% unnest(tidied_fit) %>% filter(term!="(Intercept)") %>% dplyr::select(gene_id, strain_id, replicate, "slope"=estimate, "slope_SE"=std.error)

# Export summary and slopes
df_export <- df_slopes %>% left_join(., df_sc_sum, by = c("gene_id", "strain_id")) #%>% left_join(., pca_results_genes %>% select(gene_id, PC1), by="gene_id") 

df_export %>% write_tsv("../../size_slopes/input_tables/elutriation-arrest_RNA_slopes.txt")
```

plotting (slope vs PC1)
```{r,warning=FALSE}
df_sum_wide <- df_slopes %>% filter(strain_id == "MS64") %>% pivot_wider(id_cols=c("gene_id"), names_from="replicate", values_from=c("slope", "slope_SE")) %>% left_join(., pca_results_genes, by="gene_id") %>% left_join(., df_sc_sum, by = c("gene_id"))

df <- df_sum_wide %>% filter(TPMmin>5)

x <- df$slope_pooled
y <- df$PC1
z <- df$slope_SE_pooled

label<- labs(title="Elutriation arrest RNA", x= "Slope (haploid)", y= "PC1", color="SE") 
axes <- lims(x= c(-2, 2), y = c(-8, 8))

bin_sum <- Hmisc::cut2(x, g=50) %>% bind_cols(., x, y) %>% dplyr::rename("bins"=1,"x"=2,"y"=3) %>% drop_na() %>% dplyr::group_by(bins) %>% summarise(sd=sd(y, na.rm = TRUE), x=mean(x), y=mean(y), n = n())

points <- df %>% geom_point(mapping = aes(x=(x), y=(y), color=(z), text=paste("gene_name:", gene_name)),  size=2, alpha=0.35) 
binned_line <- bin_sum %>% geom_line(mapping = aes(x=(x), y=(y)))
annotate <- annotate(geom = 'text', label =  paste("pearson =", (corrr::correlate(x=x, y=y, method="pearson")$x %>% round(digits = 3))), x=-Inf, y=Inf, hjust=-0.15, vjust=2.5)
color <- scale_color_viridis(begin=0.15, end=1, limits=c(), oob=scales::squish)

plot_slope <- ggplot() + points + label + annotate + color + axes + binned_line + coord_fixed(ratio = 0.25)
plot_slope
ggsave(plot_slope, filename = "../figures/haploid_slope-v-PC1_elutriation-arrest_RNA.svg", dpi = 300, width = 4, height = 3)
```
