---
title: "RPKM table for spike-in normalised ChIP-seq of elutriation arrested SCGE cells"
author: "MH"
date: "2024-05-27"
output: html_document
---
```{r setup}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path)) 
rm(list=ls())
library(MASS)
library(plotly)
library(broom)
library(corrr)
library(nls.multstart)
library(viridis)
library(tidyverse)
load('../../r_functions/functions.rda')
```
Process tables
```{r}
# Load tables
sample_info <- read_tsv("../input_tables/sample_info.txt", show_col_types=FALSE)
df1 <- read_tsv("../input_tables/genes.with_multimappers.nochrM.ERMTOC.fragmentMidPoint.sacCer3.RPKM.table.txt", show_col_types=FALSE) %>% rename("chr"=1, "gene_id"=5, "gene_name"=6)

# Filter for genes with RPKM > 0 in all samples, pivot RPKM longer, normalize RPKM
df2 <- df1 %>% select(gene_id, gene_name, contains("exp")) %>% filter_at(vars(contains("exp")), all_vars(.>0)) %>% pivot_longer(cols=colnames(dplyr::select(., contains("exp"))), names_to="sample", values_to="RPKM") %>% group_by(sample) %>% mutate(RPKM_rescaled=((RPKM/sum(RPKM))*10^6)) %>% ungroup()

# Combine with sample info, filter for genes with valid mean cell size (Strain MS64/67)
df3 <- df2 %>% left_join(., sample_info, by="sample") %>% filter(., mean_cell_size>0)

# Calculate mean of each gene for each antibody in a given replicate 
df_rep_mean <- df3 %>% summarise(.by=c(gene_id, gene_name, antibody, replicate), RPKM_rescaled_mean_rep=mean(RPKM_rescaled))
# Calculate min of each gene for each antibody
df_sum <- df3 %>% summarise(.by=c(gene_id, gene_name, strain_id, antibody), RPKM_rescaled_min=min(RPKM_rescaled), RPKM_rescaled_mean=mean(RPKM_rescaled)) %>% left_join(., summarise(filter(df3, time_point=="T3"), .by=c(gene_id, strain_id), RPKMrefm=mean(RPKM_rescaled))) %>% left_join(., summarise(filter(df3, time_point=="T1"), .by=c(gene_id, strain_id), RPKMrefs=mean(RPKM_rescaled)))

df_sc <- left_join(df3, df_sum, by=c('gene_id', 'gene_name', 'strain_id', 'antibody')) %>% left_join(., df_rep_mean, by=c("gene_id", "gene_name", "antibody", "replicate")) %>% mutate(RPKMnorm=RPKM_rescaled/RPKM_rescaled_mean_rep) %>% mutate(log2RPKMnorm = log2(RPKMnorm)) %>% mutate(log2_norm_cell_size = log2(mean_cell_size/mean(mean_cell_size)))
```
PCA
```{r}
#principle component analysis on all genes with minimum RPKM > 2
df_pca <- df_sc %>% filter(antibody=="Rpb1") %>% filter(RPKM_rescaled_min>2) %>% dplyr::select(gene_id, sample, log2RPKMnorm) %>% pivot_wider(id_cols=c("gene_id"), names_from="sample", values_from=c("log2RPKMnorm")) %>% drop_na()

pca <- df_pca %>% dplyr::select(., where(is.numeric)) %>% prcomp(scale.=FALSE, center=FALSE)

pca_results_variance <- summary(pca)$importance[2,] %>% as.data.frame()
pca_results_samples <- as.data.frame(pca$rotation) %>% rownames_to_column(var="sample") %>% left_join(., sample_info)
pca_results_genes <- bind_cols(dplyr::select(df_pca, gene_id), as.data.frame(pca$x))

label<-labs(y="PC1", x="Mean Cell Size (fL)", color="Strain ID", title="Elutriation-arrest ChIP") 

plot_pca <- pca_results_samples %>% ggplot(aes(x=mean_cell_size, y=PC1, color=strain_id, text=paste("", sample))) + geom_point( size=3, alpha=0.85) +  viridis::scale_color_viridis(discrete=TRUE) + coord_fixed(ratio = 200) + label
plot_pca
ggsave(plot_pca, filename = "../figures/PC1-v-size_elutriation-arrest_ChIP_Rpb1.svg", dpi = 300, width = 4, height = 3)
```
Correlation analysis
```{r}
# Calculate correlations between selected RPKM values, convert to tidy format and plot
df_corr <- df_sc %>% filter(antibody=="Rpb1") %>% filter(RPKM_rescaled_min>2) %>% select(gene_id, sample_short, var=log2RPKMnorm) %>% pivot_wider(id_cols=c("gene_id") , names_from="sample_short", values_from=c("var"))

plot_cor <- plot_corr(df_corr, title="Elutriation arrest ChIP", angle=75, show_corr=F)
plot_cor
ggsave(plot_cor, filename = "../figures/pearson-heatmap_elutriation-arrest_ChIP_Rpb1.svg", dpi = 300, width = 10, height = 7.5)
```
Linear regression
```{r}
# Construct linear models for average of replicates, save the slope and SE 
df_fit_pooled <- df_sc %>% nest(data = c(-gene_id, -antibody, -strain_id)) %>% slope_fit(a="log2RPKMnorm",b="log2_norm_cell_size") %>% mutate(replicate="pooled")

# Construct linear models for each replicate separately
df_fit_exp <- df_sc %>% nest(data = c(-gene_id, -antibody, -strain_id, -replicate)) %>% slope_fit(a="log2RPKMnorm",b="log2_norm_cell_size")

df_slopes <- bind_rows(df_fit_exp, df_fit_pooled) %>% unnest(tidied_fit) %>% filter(term!="(Intercept)") %>% dplyr::select(gene_id, strain_id, antibody, replicate, "slope"=estimate, "slope_SE"=std.error)

df_export <- df_slopes %>% left_join(., df_sum, by = c("gene_id", "strain_id", "antibody"))
df_export %>% write_tsv("../../size_slopes/input_tables/elutriation-arrest_ChIP_slopes.txt")
```
Plot slopes against PC1
```{r}
df_sum_wide <- df_slopes %>% filter(strain_id == "MS64") %>% pivot_wider(id_cols=c("gene_id", "replicate"), names_from="antibody", values_from=c("slope", "slope_SE")) %>% left_join(., pca_results_genes, by="gene_id") %>% left_join(., df_sum, by = c("gene_id"))

df <- df_sum_wide %>% filter(antibody == "Rpb1") %>% filter(RPKM_rescaled_min >5) %>% rowwise()

x <- df$slope_Rpb1
y <- df$PC1
z <- df$slope_SE_Rpb1

label<- labs(title="Elutriation arrest ChIP", x= "Slope", y= "PC1", color='SE') 
axes <- lims(x= c(-2, 2), y = c(-8, 8))

bin_sum <- Hmisc::cut2(x, g=50) %>% bind_cols(., x, y) %>% dplyr::rename("bins"=1,"x"=2,"y"=3) %>% drop_na() %>% dplyr::group_by(bins) %>% summarise(sd=sd(y, na.rm = TRUE), x=mean(x), y=mean(y), n = n())

points <- df %>% geom_point(mapping = aes(x=(x), y=(y), color=(z), text=paste("gene_name:", gene_name)),  size=2, alpha=0.35) 
binned_line <- bin_sum %>% geom_line(mapping = aes(x=(x), y=(y)))
annotate <- annotate(geom = 'text', label =  paste("pearson =", (corrr::correlate(x=x, y=y, method="pearson")$x %>% round(digits = 3))), x=-Inf, y=Inf, hjust=-0.15, vjust=2.5)
color <- scale_color_viridis(begin=0.15, end=1, limits=c(), oob=scales::squish)

plot_slope <- ggplot() + points + label + annotate + color + axes + binned_line + coord_fixed(ratio = 0.25)
plot_slope
ggsave(plot_slope, filename = "../figures/slope-v-PC1_elutriation-arrest_ChIP.svg", dpi = 300, width = 4, height = 3)
```
